openapi: 3.0.0
info:
  title: "Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname
      properties:
        fname:
          type: "string"
        lname:
          type: "string"
    Task:
      type: "object"
      required:
        - name
      properties:
        name:
          type: "string"
        comment:
          type: "string"
        due_date:
          type: "string"
          format: "date"
  parameters:
    lname:
      name: "lname"
      description: "Last name of the person to get"
      in: path
      required: True
      schema:
        type: "string"
    name:
      name: "name"
      description: "Name of the task to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
    post:
      operationId: "people.create"
      tags:
        - People
      summary: "Create a person"
      requestBody:
          description: "Person to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "person"
                $ref: "#/components/schemas/Person"
      responses:
        "201":
          description: "Successfully created person"
  /people/{lname}:
    get:
      operationId: "people.read_one"
      tags:
        - People
      summary: "Read one person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully read person"
    put:
      tags:
        - People
      operationId: "people.update"
      summary: "Update a person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully updated person"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
    delete:
      tags:
        - People
      operationId: "people.delete"
      summary: "Delete a person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "204":
          description: "Successfully deleted person"
  /tasks:
    get:
      operationId: "tasks.read_all"
      tags:
        - "Tasks"
      summary: "Read the list of tasks"
      responses:
        "200":
          description: "Successfully read tasks list"
    post:
      operationId: "tasks.create"
      tags:
        - "Tasks"
      summary: "Create a task"
      requestBody:
          description: "Task to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "task"
                $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: "Successfully created task"
  /task/{name}:
    get:
      operationId: "tasks.read_one"
      tags:
        - "Tasks"
      summary: "Read one task"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully read task"
    put:
      tags:
        - "Tasks"
      operationId: "tasks.update"
      summary: "Update a task"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully updated task"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "task"
              $ref: "#/components/schemas/Task"
    delete:
      tags:
        - "Tasks"
      operationId: "tasks.delete"
      summary: "Delete a task"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "204":
          description: "Successfully deleted task"
